versions = ['2002',
                '2003',
                '2004',
                '2005',
                '06',
                '07',
                '08',
                '09',
                '10',
                '11',
                '12',
                '13',
                '15',
                '16',
                '17',
                '18',
                '19',
                '20',
                '25']

def get_teams(version):
    if version == '2002':
        # No Houston Texans Data
        teams = ['buffalo_bills',
                 'miami_dolphins',
                 'new_england_patriots',
                 'new_york_jets',
                 'baltimore_ravens',
                 'cincinnati_bengals',
                 'cleveland_browns',
                 'pittsburgh_steelers',
                 'indianapolis_colts',
                 'jacksonville_jaguars',
                 'tennessee_titans',
                 'denver_broncos',
                 'kansas_city_chiefs',
                 'oakland_raiders',
                 'san_diego_chargers',
                 'dallas_cowboys',
                 'philadelphia_eagles',
                 'washington_redskins',
                 'new_york_giants',
                 'chicago_bears',
                 'detroit_lions',
                 'green_bay_packers',
                 'minnesota_vikings',
                 'atlanta_falcons',
                 'carolina_panthers',
                 'new_orleans_saints',
                 'tampa_bay_buccaneers',
                 'arizona_cardinals',
                 'st._louis_rams',
                 'san_francisco_49ers',
                 'seattle_seahawks']

    elif int(version) in range(2003, 2006) or int(version) in range(6, 17) or version == '25':
        teams = ['buffalo_bills',
                 'miami_dolphins',
                 'new_england_patriots',
                 'new_york_jets',
                 'baltimore_ravens',
                 'cincinnati_bengals',
                 'cleveland_browns',
                 'pittsburgh_steelers',
                 'indianapolis_colts',
                 'jacksonville_jaguars',
                 'tennessee_titans',
                 'denver_broncos',
                 'kansas_city_chiefs',
                 'oakland_raiders',
                 'san_diego_chargers',
                 'dallas_cowboys',
                 'philadelphia_eagles',
                 'washington_redskins',
                 'new_york_giants',
                 'chicago_bears',
                 'detroit_lions',
                 'green_bay_packers',
                 'minnesota_vikings',
                 'atlanta_falcons',
                 'carolina_panthers',
                 'new_orleans_saints',
                 'tampa_bay_buccaneers',
                 'arizona_cardinals',
                 'st._louis_rams',
                 'san_francisco_49ers',
                 'seattle_seahawks',
                 'houston_texans']

    elif version == '17':
        # LA Rams
        teams = ['buffalo_bills',
                 'miami_dolphins',
                 'new_england_patriots',
                 'new_york_jets',
                 'baltimore_ravens',
                 'cincinnati_bengals',
                 'cleveland_browns',
                 'pittsburgh_steelers',
                 'indianapolis_colts',
                 'jacksonville_jaguars',
                 'tennessee_titans',
                 'denver_broncos',
                 'kansas_city_chiefs',
                 'oakland_raiders',
                 'san_diego_chargers',
                 'dallas_cowboys',
                 'philadelphia_eagles',
                 'washington_redskins',
                 'new_york_giants',
                 'chicago_bears',
                 'detroit_lions',
                 'green_bay_packers',
                 'minnesota_vikings',
                 'atlanta_falcons',
                 'carolina_panthers',
                 'new_orleans_saints',
                 'tampa_bay_buccaneers',
                 'arizona_cardinals',
                 'los_angeles_rams',
                 'san_francisco_49ers',
                 'seattle_seahawks',
                 'houston_texans']

    elif int(version) in range(18, 21):
        # LA Chargers
        teams = ['buffalo_bills',
                 'miami_dolphins',
                 'new_england_patriots',
                 'new_york_jets',
                 'baltimore_ravens',
                 'cincinnati_bengals',
                 'cleveland_browns',
                 'pittsburgh_steelers',
                 'indianapolis_colts',
                 'jacksonville_jaguars',
                 'tennessee_titans',
                 'denver_broncos',
                 'kansas_city_chiefs',
                 'oakland_raiders',
                 'los_angeles_chargers',
                 'dallas_cowboys',
                 'philadelphia_eagles',
                 'washington_redskins',
                 'new_york_giants',
                 'chicago_bears',
                 'detroit_lions',
                 'green_bay_packers',
                 'minnesota_vikings',
                 'atlanta_falcons',
                 'carolina_panthers',
                 'new_orleans_saints',
                 'tampa_bay_buccaneers',
                 'arizona_cardinals',
                 'los_angeles_rams',
                 'san_francisco_49ers',
                 'seattle_seahawks',
                 'houston_texans']

    else:
        raise ValueError('No data for this version!')

    return teams

def get_name(team):
    teams = {'buffalo_bills':'Bills',
             'miami_dolphins':'Dolphins',
             'new_england_patriots':'Patriots',
             'new_york_jets':'Jets',
             'baltimore_ravens':'Ravens',
             'cincinnati_bengals':'Bengals',
             'cleveland_browns':'Browns',
             'pittsburgh_steelers':'Steelers',
             'indianapolis_colts':'Colts',
             'jacksonville_jaguars':'Jaguars',
             'tennessee_titans':'Titans',
             'denver_broncos':'Broncos',
             'kansas_city_chiefs':'Chiefs',
             'oakland_raiders':'Raiders',
             'los_angeles_chargers':'Chargers',
             'dallas_cowboys':'Cowboys',
             'philadelphia_eagles':'Eagles',
             'washington_redskins':'Redskins',
             'new_york_giants':'Giants',
             'chicago_bears':'Bears',
             'detroit_lions':'Lions',
             'green_bay_packers':'Packers',
             'minnesota_vikings':'Vikings',
             'atlanta_falcons':'Falcons',
             'carolina_panthers':'Panthers',
             'new_orleans_saints':'Saints',
             'tampa_bay_buccaneers':'Buccaneers',
             'arizona_cardinals':'Cardinals',
             'los_angeles_rams':'Rams',
             'san_francisco_49ers':'49ers',
             'seattle_seahawks':'Seahawks',
             'houston_texans':'Texans',
             'st._louis_rams':'Rams',
             'san_diego_chargers':'Chargers'}

    return teams[team]